{application,chumak,
             [{description,"Erlang implementation of ZeroMQ Transport Protocol (ZMTP)"},
              {vsn,"1.3.0"},
              {registered,[]},
              {mod,{chumak,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[chumak,chumak_bind,chumak_cert,chumak_command,
                        chumak_curve,chumak_curve_if,chumak_dealer,chumak_lb,
                        chumak_lbs,chumak_pair,chumak_pattern,chumak_peer,
                        chumak_protocol,chumak_pub,chumak_pull,chumak_push,
                        chumak_rep,chumak_req,chumak_resource,chumak_router,
                        chumak_socket,chumak_sub,chumak_subscriptions,
                        chumak_sup,chumak_xpub,chumak_xsub,chumak_z85]},
              {maintainers,["Andriy Drozdyuk"]},
              {licenses,["MPLv2"]},
              {links,[{"Github","https://github.com/chovencorp/chumak"}]}]}.
