template: Diretorio, %s!
districts: ['Braga','VianaDoCastelo','VilaReal','CasteloBranco','Leiria','Lisboa','Porto','Evora','Beja','Faro','Portalegre','Coimbra','Braganca','Aveiro','Santarem','Setubal','Guarda','Viseu']
