template: Diretorio, %s!
districts: ['Braga','Viana Do Castelo','Vila Real','Castelo Branco','Leiria','Lisboa','Porto','Evora','Beja','Faro','Portalegre','Coimbra','Braganca','Aveiro','Santarem','Setubal','Guarda','Viseu']
