[default]
"NR_DISTRICTS"     = 18
[ports]
"FRONTEND"         = 10000
"CENTRAL_SERVER"   = 10100
[local]
"Braga"            = 1
"Aveiro"           = 2
"Beja"             = 3
"Braganca"         = 4
"Castelo Branco"   = 5
"Coimbra"          = 6
"Evora"            = 7
"Faro"             = 8
"Lisboa"           = 9
"Guarda"           = 10
"Portalegre"       = 11
"Porto"            = 12
"Santarem"         = 13
"Setubal"          = 14
"Viana do Castelo" = 15
"Vila Real"        = 16
"Viseu"            = 17
"Leiria"           = 18